livereload: true

# Site settings
title: Cap'n Adrián Mato – Product Designer in San Francisco
email: hello@adrianmato.com
baseurl: "" # the subpath of your site, e.g. /blog
baseurl_blog: "/blog" # the subpath of the blog
url: "https://adrianmato.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Adrián Mato
twitter: adrianmg
bluesky: adrianmato.com
linkedin: adrianmg
github: adrianmg
instagram: adrianmato

# Custom Settings
timezone: America/Los_Angeles
permalink: /:categories/:title/

# Build settings
markdown: kramdown
incremental: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
include:
  - 404.html
