livereload: true

# Site settings
title: Adrian Mato â€“ Product Designer in San Francisco
email: hello@adrianmato.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Adrian Mato. Designing and building tools for developers at Microsoft.
baseurl: "" # the subpath of your site, e.g. /blog
baseurl_blog: "/blog" # the subpath of the blog
url: "http://adrianmato.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Adrian Mato
twitter_username: adrianmg
linkedin_username: adrianmg
github_username:  adrianmg
instagram_username: adrianmato

# Custom Settings
timezone: America/Los_Angeles
permalink: /:categories/:title/

# Build settings
markdown: kramdown
incremental: true

plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
